# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: 'Auto label PR based on branch name'
description: 'A GitHub action.'
author: 'kiwiupover'

branding:
  icon: 'PR'
  color: 'blue'

inputs:
  token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true

outputs:
 result:
   description: action result

runs:
  using: 'node16'
  main: 'dist/index.js'
