name: Auto Label PR based on brach

on: [push, pull_request]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Auto PR label
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the output time
        run: echo "The time was ${{ steps.auto_pr_label.outputs.time }}"
